node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('docker build/push') {
      def newBuild = docker.build "terrygao8/pipeline:{env.BUILD_TAG}"
   }
}
